apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80


# kubectl expose deployment nginx --port=80 --type=LoadBalancer
# kubectl port-forward svc/nginx 8080:80
# kubectl get svc nginx -w
