apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 3 # the desired number of replicas
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image:  si3mshady/awsthree:2
          ports:
            - containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  selector:
    app: react-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
